api_platform:
    title: 'Motoo Planner API'
    description: 'A Symfony API to manage Motoo Planner App.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
