api_platform:
    title: 'Motoo Planner API'
    description: 'A Symfony API to manage Motoo Planner App.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    # The list of enabled formats. The first one will be the default.
    formats:
        jsonld:
            mime_types: [ 'application/ld+json' ]
        json:
            mime_types: [ 'application/json' ]
        jsonhal:
            mime_types: [ 'application/hal+json' ]
        html:
            mime_types: [ 'text/html' ]
        csv:
            mime_types: ['text/csv']
        multipart:
            mime_types: ['multipart/form-data']


    # The list of enabled patch formats. The first one will be the default.
    patch_formats:
        json: ['application/merge-patch+json']
        multipart: ['multipart/form-data']

    swagger:
        versions: [3]
