vich_uploader:
    db_driver: orm

    mappings:
        # nom pour identifier la propriété et le chemin qui stocke les images
        article_pictures:
            uri_prefix: '%app.path.article_pictures%'
            upload_destination: '%kernel.project_dir%/public%app.path.article_pictures%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            # pour générer des clés unique pour chacun des fichiers (au lieu d'avoir le nom)
        roadbook_pictures:
            uri_prefix: '%app.path.roadbook_pictures%'
            upload_destination: '%kernel.project_dir%/public%app.path.roadbook_pictures%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
