vich_uploader:
    db_driver: orm

    mappings:
        # nom pour identifier la propriété et le chemin qui stocke les images
        article_pictures:
            uri_prefix: '%app.path.article_pictures%'
            upload_destination: '%kernel.project_dir%/public%app.path.article_pictures%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            # pour générer des clés unique pour chacun des fichiers (au lieu d'avoir le nom)

        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
